apiVersion: v1
kind: Service 
metadata:
  name: nagp-k8s-assign-lb-service
spec:
  type: LoadBalancer
  selector:
    app: nagp-k8s-assign
  ports: 
    - name: http
      port: 80 
      targetPort: 9090
